# Utiliser l'image Maven pour compiler le projet
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Utiliser une image OpenJDK pour exécuter l'application
FROM openjdk:17
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Exposer le port de l'API
EXPOSE 8080

# Démarrer Spring Boot
CMD ["java", "-jar", "app.jar"]
